# Generated by Django 5.2.12 on 2026-03-13 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistencia_django", "0006_producto_campos_publicos"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeccionPublicaModelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("nombre", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True, default="")),
                ("orden", models.PositiveIntegerField(default=100)),
                ("publicada", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "sección pública",
                "verbose_name_plural": "secciones públicas",
                "db_table": "nucleo_seccion_publica",
                "ordering": ("orden", "nombre"),
            },
        ),
        migrations.CreateModel(
            name="ArticuloEditorialModelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("titulo", models.CharField(max_length=200)),
                ("resumen", models.TextField(blank=True, default="")),
                ("contenido", models.TextField()),
                ("tema", models.CharField(blank=True, default="", max_length=120)),
                ("hub", models.CharField(blank=True, default="", max_length=120)),
                ("subhub", models.CharField(blank=True, default="", max_length=120)),
                (
                    "imagen_url",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("indexable", models.BooleanField(default=True)),
                ("publicado", models.BooleanField(default=False)),
                ("fecha_publicacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "seccion_publica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articulos",
                        to="persistencia_django.seccionpublicamodelo",
                    ),
                ),
            ],
            options={
                "verbose_name": "artículo editorial",
                "verbose_name_plural": "artículos editoriales",
                "db_table": "nucleo_articulo_editorial",
                "ordering": ("-fecha_actualizacion", "titulo"),
            },
        ),
        migrations.AddField(
            model_name="productomodelo",
            name="orden_publicacion",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="ritualmodelo",
            name="contenido",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ritualmodelo",
            name="imagen_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddIndex(
            model_name="articuloeditorialmodelo",
            index=models.Index(
                fields=["publicado", "indexable", "slug"],
                name="nucleo_arti_publica_5a7cfa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="articuloeditorialmodelo",
            index=models.Index(
                fields=["tema", "hub", "subhub"], name="nucleo_arti_tema_a22241_idx"
            ),
        ),
    ]
