# Generated by Django 5.2.12 on 2026-03-13 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "persistencia_django",
            "0007_articuloeditorialmodelo_seccionpublicamodelo_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cuentademomodelo",
            options={
                "ordering": ("email",),
                "verbose_name": "cuenta demo",
                "verbose_name_plural": "cuentas demo",
            },
        ),
        migrations.AlterModelOptions(
            name="intencionmodelo",
            options={
                "ordering": ("nombre",),
                "verbose_name": "intención",
                "verbose_name_plural": "intenciones",
            },
        ),
        migrations.AlterModelOptions(
            name="lineapedidomodelo",
            options={
                "ordering": ("id",),
                "verbose_name": "línea de pedido demo",
                "verbose_name_plural": "líneas de pedido demo",
            },
        ),
        migrations.AlterModelOptions(
            name="pedidodemomodelo",
            options={
                "ordering": ("-fecha_creacion",),
                "verbose_name": "pedido demo",
                "verbose_name_plural": "pedidos demo",
            },
        ),
        migrations.AlterModelOptions(
            name="plantamodelo",
            options={
                "ordering": ("nombre",),
                "verbose_name": "planta",
                "verbose_name_plural": "plantas",
            },
        ),
        migrations.AlterModelOptions(
            name="productomodelo",
            options={
                "ordering": ("orden_publicacion", "nombre"),
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
            },
        ),
        migrations.AlterModelOptions(
            name="reglacalendariomodelo",
            options={
                "ordering": ("prioridad", "id"),
                "verbose_name": "regla de calendario",
                "verbose_name_plural": "reglas de calendario",
            },
        ),
        migrations.AlterModelOptions(
            name="ritualmodelo",
            options={
                "ordering": ("nombre",),
                "verbose_name": "ritual",
                "verbose_name_plural": "rituales",
            },
        ),
        migrations.AlterField(
            model_name="plantamodelo",
            name="intenciones",
            field=models.ManyToManyField(
                help_text="Intenciones editoriales vinculadas al descubrimiento herbal.",
                related_name="plantas",
                to="persistencia_django.intencionmodelo",
            ),
        ),
        migrations.AlterField(
            model_name="productomodelo",
            name="planta",
            field=models.ForeignKey(
                blank=True,
                help_text="Planta asociada cuando el producto es herbal.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productos",
                to="persistencia_django.plantamodelo",
            ),
        ),
    ]
