# Generated by Django 5.2.12 on 2026-03-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistencia_django", "0009_importacion_staging"),
    ]

    operations = [
        migrations.AddField(
            model_name="articuloeditorialmodelo",
            name="productos_relacionados",
            field=models.ManyToManyField(
                blank=True,
                help_text="Productos relacionados con el artículo para continuidad comercial.",
                related_name="articulos_editoriales",
                to="persistencia_django.productomodelo",
            ),
        ),
    ]
