# Generated by Django 5.2.12 on 2026-03-23 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistencia_django", "0021_direcciones_cuenta_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventarioProductoModelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_disponible", models.PositiveIntegerField(default=0)),
                (
                    "umbral_bajo_stock",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "producto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventario",
                        to="persistencia_django.productomodelo",
                    ),
                ),
            ],
            options={
                "verbose_name": "inventario de producto",
                "verbose_name_plural": "inventarios de producto",
                "db_table": "nucleo_inventario_producto",
                "ordering": ("producto__nombre",),
                "indexes": [
                    models.Index(
                        fields=["cantidad_disponible"], name="nucleo_inv_cantidad_idx"
                    ),
                    models.Index(
                        fields=["umbral_bajo_stock"], name="nucleo_inv_umbral_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("cantidad_disponible__gte", 0)),
                        name="nucleo_inv_cantidad_no_negativa",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("umbral_bajo_stock__isnull", True),
                            ("umbral_bajo_stock__gte", 0),
                            _connector="OR",
                        ),
                        name="nucleo_inv_umbral_no_negativo",
                    ),
                ],
            },
        ),
    ]
