# Generated by Django 5.2.12 on 2026-03-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistencia_django", "0027_envio_estandar_pedido_real"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventarioproductomodelo",
            name="unidad_base",
            field=models.CharField(
                choices=[("ud", "unidad"), ("g", "gramo"), ("ml", "mililitro")],
                default="ud",
                max_length=2,
            ),
        ),
        migrations.AddConstraint(
            model_name="inventarioproductomodelo",
            constraint=models.CheckConstraint(
                condition=models.Q(("unidad_base__in", ("ud", "g", "ml"))),
                name="nucleo_inv_unidad_base_valida",
            ),
        ),
    ]
