# Generated by Django 5.2.12 on 2026-03-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistencia_django", "0028_inventarioproductomodelo_unidad_base_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productomodelo",
            name="cantidad_minima_compra",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="productomodelo",
            name="incremento_minimo_venta",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="productomodelo",
            name="unidad_comercial",
            field=models.CharField(
                choices=[("ud", "unidad"), ("g", "gramo"), ("ml", "mililitro")],
                default="ud",
                max_length=2,
            ),
        ),
        migrations.AddConstraint(
            model_name="productomodelo",
            constraint=models.CheckConstraint(
                condition=models.Q(("unidad_comercial__in", ("ud", "g", "ml"))),
                name="nucleo_producto_unidad_comercial_valida",
            ),
        ),
        migrations.AddConstraint(
            model_name="productomodelo",
            constraint=models.CheckConstraint(
                condition=models.Q(("incremento_minimo_venta__gt", 0)),
                name="nucleo_producto_incremento_minimo_positivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="productomodelo",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad_minima_compra__gt", 0)),
                name="nucleo_producto_cantidad_minima_positiva",
            ),
        ),
    ]
