# Generated by Django 5.2.12 on 2026-03-24 21:02

from django.db import migrations, models
from django.db.models import F


def _copiar_cantidad_historica(apps, _schema_editor):
    modelo = apps.get_model("persistencia_django", "LineaPedidoRealModelo")
    modelo.objects.update(cantidad_comercial=F("cantidad"))


def _noop_reverse(_apps, _schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("persistencia_django", "0029_productomodelo_cantidad_minima_compra_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineapedidorealmodelo",
            name="cantidad_comercial",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="lineapedidorealmodelo",
            name="unidad_comercial",
            field=models.CharField(default="ud", max_length=8),
        ),
        migrations.RunPython(_copiar_cantidad_historica, _noop_reverse),
    ]
