# Generated by Django 5.2.12 on 2026-03-24 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "persistencia_django",
            "0030_lineapedidorealmodelo_cantidad_comercial_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimientoInventarioModelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("alta_inicial", "Alta inicial"),
                            ("ajuste_manual", "Ajuste manual"),
                            ("descuento_pago", "Descuento pago"),
                            ("restitucion_manual", "Restitución manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cantidad", models.IntegerField()),
                (
                    "unidad_base",
                    models.CharField(
                        choices=[("ud", "unidad"), ("g", "gramo"), ("ml", "mililitro")],
                        max_length=2,
                    ),
                ),
                (
                    "referencia",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "operation_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "inventario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="persistencia_django.inventarioproductomodelo",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimiento de inventario",
                "verbose_name_plural": "movimientos de inventario",
                "db_table": "nucleo_movimiento_inventario",
                "ordering": ("-fecha_creacion", "-id"),
                "indexes": [
                    models.Index(
                        fields=["inventario", "fecha_creacion"],
                        name="mov_inv_inv_fecha_idx",
                    ),
                    models.Index(
                        fields=["tipo_movimiento", "fecha_creacion"],
                        name="mov_inv_tipo_fecha_idx",
                    ),
                    models.Index(fields=["operation_id"], name="mov_inv_op_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("cantidad", 0), _negated=True),
                        name="mov_inv_cant_no_cero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("unidad_base__in", ("ud", "g", "ml"))),
                        name="mov_inv_unidad_valida",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "tipo_movimiento__in",
                                (
                                    "alta_inicial",
                                    "ajuste_manual",
                                    "descuento_pago",
                                    "restitucion_manual",
                                ),
                            )
                        ),
                        name="mov_inv_tipo_valido",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("operation_id", ""), _negated=True),
                        fields=("inventario", "tipo_movimiento", "operation_id"),
                        name="mov_inv_operacion_unica",
                    ),
                ],
            },
        ),
    ]
