# Generated by Django 5.2.12 on 2026-03-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistencia_django", "0031_movimientoinventariomodelo"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidorealmodelo",
            name="fecha_restitucion_inventario",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedidorealmodelo",
            name="inventario_restituido",
            field=models.BooleanField(default=False),
        ),
    ]
