# Generated by Django 5.2.12 on 2026-03-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "persistencia_django",
            "0032_pedidorealmodelo_fecha_restitucion_inventario_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidorealmodelo",
            name="email_cancelacion_enviado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pedidorealmodelo",
            name="email_reembolso_enviado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pedidorealmodelo",
            name="fecha_email_cancelacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedidorealmodelo",
            name="fecha_email_reembolso",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
