# Generated by Django 5.2.12 on 2026-03-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "persistencia_django",
            "0033_pedidorealmodelo_email_cancelacion_enviado_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidorealmodelo",
            name="tipo_impositivo",
            field=models.DecimalField(decimal_places=4, default=0.21, max_digits=5),
        ),
    ]
