# Generated by Django 5.2.12 on 2026-03-25 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistencia_django", "0034_pedidorealmodelo_tipo_impositivo"),
    ]

    operations = [
        migrations.CreateModel(
            name="DevolucionPedidoModelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_apertura", models.DateTimeField(auto_now_add=True)),
                ("motivo", models.CharField(max_length=280)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierta", "Abierta"),
                            ("recibida", "Recibida"),
                            ("aceptada", "Aceptada"),
                            ("rechazada", "Rechazada"),
                            ("cerrada", "Cerrada"),
                        ],
                        default="abierta",
                        max_length=24,
                    ),
                ),
                (
                    "abierta_por",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "revisada_por",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("fecha_revision", models.DateTimeField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, default="")),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devoluciones",
                        to="persistencia_django.pedidorealmodelo",
                    ),
                ),
            ],
            options={
                "verbose_name": "devolución manual",
                "verbose_name_plural": "devoluciones manuales",
                "db_table": "nucleo_devolucion_pedido",
                "ordering": ("-fecha_apertura",),
                "indexes": [
                    models.Index(
                        fields=["estado", "fecha_apertura"],
                        name="nuc_dev_estado_fecha_idx",
                    ),
                    models.Index(
                        fields=["pedido", "fecha_apertura"],
                        name="nuc_dev_pedido_fecha_idx",
                    ),
                ],
            },
        ),
    ]
