# Generated by Django 5.2.12 on 2026-03-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistencia_django", "0035_devolucionpedidomodelo"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineapedidorealmodelo",
            name="importe_impuestos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="lineapedidorealmodelo",
            name="tipo_impositivo",
            field=models.DecimalField(decimal_places=4, default=0.21, max_digits=5),
        ),
        migrations.AddField(
            model_name="productomodelo",
            name="tipo_fiscal",
            field=models.CharField(
                choices=[
                    ("iva_general", "IVA general (21%)"),
                    ("iva_reducido", "IVA reducido (10%)"),
                ],
                default="iva_general",
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="productomodelo",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tipo_fiscal__in", ("iva_general", "iva_reducido"))
                ),
                name="nucleo_producto_tipo_fiscal_valido",
            ),
        ),
    ]
