INTENCIONES_DEMO = (
    {
        "id": "int-demo-calma",
        "slug": "calma-nocturna",
        "nombre": "Calma nocturna",
        "descripcion": "Intencion editorial para cierres suaves, descanso ritual y pausas de abrigo.",
        "es_publica": True,
    },
    {
        "id": "int-demo-limpieza",
        "slug": "limpieza-energetica",
        "nombre": "Limpieza energetica",
        "descripcion": "Intencion editorial para renovar el ambiente y limpiar el umbral del hogar.",
        "es_publica": True,
    },
    {
        "id": "int-demo-claridad",
        "slug": "claridad-ritual",
        "nombre": "Claridad ritual",
        "descripcion": "Intencion editorial para lecturas, foco y orden simbolico de mesa o altar.",
        "es_publica": True,
    },
    {
        "id": "int-demo-gratitud",
        "slug": "gratitud-cotidiana",
        "nombre": "Gratitud cotidiana",
        "descripcion": "Intencion editorial para pequenos gestos de gratitud, abundancia y recogimiento.",
        "es_publica": True,
    },
)

PLANTAS_DEMO = (
    {
        "id": "pla-demo-melisa",
        "slug": "melisa",
        "nombre": "Melisa",
        "descripcion_breve": "Planta aromatica tradicional asociada a calma, abrigo y cierre del dia.",
        "publicada": True,
        "intenciones": ("calma-nocturna",),
    },
    {
        "id": "pla-demo-romero",
        "slug": "romero",
        "nombre": "Romero",
        "descripcion_breve": "Planta mediterranea conectada a limpieza del hogar, claridad y enfoque.",
        "publicada": True,
        "intenciones": ("limpieza-energetica", "claridad-ritual"),
    },
    {
        "id": "pla-demo-lavanda",
        "slug": "lavanda",
        "nombre": "Lavanda",
        "descripcion_breve": "Flor seca de aroma limpio para bolsitas, pausas suaves y composiciones de altar.",
        "publicada": True,
        "intenciones": ("calma-nocturna",),
    },
    {
        "id": "pla-demo-manzanilla",
        "slug": "manzanilla",
        "nombre": "Manzanilla",
        "descripcion_breve": "Capitulo floral tradicional vinculado a sosiego, cuidado cotidiano y gratitud.",
        "publicada": True,
        "intenciones": ("calma-nocturna", "gratitud-cotidiana"),
    },
)

PRODUCTOS_DEMO = (
    {
        "id": "pro-demo-melisa",
        "sku": "HERB-DEMO-001",
        "slug": "melisa-a-granel-50g",
        "nombre": "Melisa a granel 50g",
        "tipo_producto": "hierbas-a-granel",
        "categoria_comercial": "hierbas-a-granel",
        "seccion_publica": "botica-natural",
        "descripcion_corta": "Hoja cortada para infusion suave de tarde y descanso ritual.",
        "precio_visible": "9,90 EUR",
        "imagen_url": "/imagenes/productos/melisa-a-granel.webp",
        "planta_slug": "melisa",
        "publicado": True,
    },
    {
        "id": "pro-demo-romero",
        "sku": "HERB-DEMO-002",
        "slug": "romero-a-granel-50g",
        "nombre": "Romero a granel 50g",
        "tipo_producto": "hierbas-a-granel",
        "categoria_comercial": "hierbas-a-granel",
        "seccion_publica": "botica-natural",
        "descripcion_corta": "Romero de corte fino para banos herbales y limpieza simbolica del hogar.",
        "precio_visible": "8,50 EUR",
        "imagen_url": "/imagenes/productos/romero-a-granel.webp",
        "planta_slug": "romero",
        "publicado": True,
    },
    {
        "id": "pro-demo-lavanda",
        "sku": "HERB-DEMO-003",
        "slug": "lavanda-flores-40g",
        "nombre": "Lavanda flores 40g",
        "tipo_producto": "inciensos-y-sahumerios",
        "categoria_comercial": "flores-herbales",
        "seccion_publica": "botica-natural",
        "descripcion_corta": "Flores secas de lavanda para sahumo suave y bolsitas aromaticas.",
        "precio_visible": "7,20 EUR",
        "imagen_url": "/imagenes/productos/lavanda-flores.webp",
        "planta_slug": "lavanda",
        "publicado": True,
    },
    {
        "id": "pro-demo-manzanilla",
        "sku": "HERB-DEMO-004",
        "slug": "manzanilla-dulce-60g",
        "nombre": "Manzanilla dulce 60g",
        "tipo_producto": "hierbas-a-granel",
        "categoria_comercial": "hierbas-a-granel",
        "seccion_publica": "botica-natural",
        "descripcion_corta": "Capitulos florales seleccionados para infusion, vapor suave y pausa domestica.",
        "precio_visible": "8,90 EUR",
        "imagen_url": "",
        "planta_slug": "manzanilla",
        "publicado": True,
    },
    {
        "id": "pro-demo-ruda",
        "sku": "HERB-DEMO-005",
        "slug": "ruda-rama-seca-30g",
        "nombre": "Ruda rama seca 30g",
        "tipo_producto": "herramientas-rituales",
        "categoria_comercial": "proteccion-del-hogar",
        "seccion_publica": "botica-natural",
        "descripcion_corta": "Atado ritual para limpieza del umbral y proteccion simbolica.",
        "precio_visible": "6,40 EUR",
        "imagen_url": "/imagenes/productos/ruda-rama-seca.webp",
        "planta_slug": None,
        "publicado": True,
    },
    {
        "id": "pro-demo-vela",
        "sku": "HERB-DEMO-900",
        "slug": "vela-lunar-blanca",
        "nombre": "Vela lunar blanca",
        "tipo_producto": "herramientas-rituales",
        "categoria_comercial": "velas",
        "seccion_publica": "velas-e-incienso",
        "descripcion_corta": "Pieza de apoyo para altar lunar y cierres serenos de final del dia.",
        "precio_visible": "5,00 EUR",
        "imagen_url": "/imagenes/productos/vela-lunar-blanca.webp",
        "planta_slug": None,
        "publicado": True,
    },
    {
        "id": "pro-demo-incienso-ruda",
        "sku": "HERB-DEMO-901",
        "slug": "incienso-ruda-proteccion",
        "nombre": "Incienso de ruda proteccion",
        "tipo_producto": "inciensos-y-sahumerios",
        "categoria_comercial": "inciensos",
        "seccion_publica": "velas-e-incienso",
        "descripcion_corta": "Varillas de ruda para limpiar el ambiente y acompanar aperturas rituales.",
        "precio_visible": "4,80 EUR",
        "imagen_url": "/imagenes/productos/incienso-ruda-proteccion.webp",
        "planta_slug": None,
        "publicado": True,
    },
    {
        "id": "pro-demo-vela-miel",
        "sku": "HERB-DEMO-902",
        "slug": "vela-miel-dorada",
        "nombre": "Vela miel dorada",
        "tipo_producto": "herramientas-rituales",
        "categoria_comercial": "velas",
        "seccion_publica": "velas-e-incienso",
        "descripcion_corta": "Vela de cera para altares calidos y practicas de gratitud cotidiana.",
        "precio_visible": "6,20 EUR",
        "imagen_url": "/imagenes/productos/vela-miel-dorada.webp",
        "planta_slug": None,
        "publicado": True,
    },
    {
        "id": "pro-demo-cuarzo",
        "sku": "HERB-DEMO-950",
        "slug": "cuarzo-cristal-rodado",
        "nombre": "Cuarzo cristal rodado",
        "tipo_producto": "minerales-y-piedras",
        "categoria_comercial": "rodados",
        "seccion_publica": "minerales-y-energia",
        "descripcion_corta": "Pieza pulida de cuarzo transparente para altar, bolsillo ritual o escritorio.",
        "precio_visible": "7,50 EUR",
        "imagen_url": "/imagenes/productos/cuarzo-cristal-rodado.webp",
        "planta_slug": None,
        "publicado": True,
    },
    {
        "id": "pro-demo-amatista",
        "sku": "HERB-DEMO-951",
        "slug": "amatista-punta-suave",
        "nombre": "Amatista punta suave",
        "tipo_producto": "minerales-y-piedras",
        "categoria_comercial": "puntas",
        "seccion_publica": "minerales-y-energia",
        "descripcion_corta": "Punta de amatista para pausa, lectura simbolica y focos de trabajo sereno.",
        "precio_visible": "12,90 EUR",
        "imagen_url": "/imagenes/productos/amatista-punta-suave.webp",
        "planta_slug": None,
        "publicado": True,
    },
    {
        "id": "pro-demo-obsidiana",
        "sku": "HERB-DEMO-952",
        "slug": "obsidiana-negra-bruta",
        "nombre": "Obsidiana negra bruta",
        "tipo_producto": "minerales-y-piedras",
        "categoria_comercial": "piedra-bruta",
        "seccion_publica": "minerales-y-energia",
        "descripcion_corta": "Fragmento mineral en bruto para composiciones de altar y contraste materico.",
        "precio_visible": "9,80 EUR",
        "imagen_url": "/imagenes/productos/obsidiana-negra-bruta.webp",
        "planta_slug": None,
        "publicado": True,
    },
    {
        "id": "pro-demo-pendulo",
        "sku": "HERB-DEMO-980",
        "slug": "pendulo-laton-dorado",
        "nombre": "Pendulo de laton dorado",
        "tipo_producto": "herramientas-rituales",
        "categoria_comercial": "radiestesia",
        "seccion_publica": "herramientas-esotericas",
        "descripcion_corta": "Herramienta de consulta simbolica para altar, diario ritual o mesa de trabajo.",
        "precio_visible": "14,90 EUR",
        "imagen_url": "/imagenes/productos/pendulo-laton-dorado.webp",
        "planta_slug": None,
        "publicado": True,
    },
    {
        "id": "pro-demo-cuenco-selenita",
        "sku": "HERB-DEMO-981",
        "slug": "cuenco-selenita-pulido",
        "nombre": "Cuenco de selenita pulido",
        "tipo_producto": "herramientas-rituales",
        "categoria_comercial": "altar-y-soportes",
        "seccion_publica": "herramientas-esotericas",
        "descripcion_corta": "Pieza de apoyo para guardar amuletos, mezclas secas o pequenas piedras del altar.",
        "precio_visible": "18,50 EUR",
        "imagen_url": "/imagenes/productos/cuenco-selenita-pulido.webp",
        "planta_slug": None,
        "publicado": True,
    },
    {
        "id": "pro-demo-caldero",
        "sku": "HERB-DEMO-982",
        "slug": "caldero-hierro-mini",
        "nombre": "Caldero de hierro mini",
        "tipo_producto": "herramientas-rituales",
        "categoria_comercial": "altares-y-fuego",
        "seccion_publica": "herramientas-esotericas",
        "descripcion_corta": "Recipiente de mesa para carbon, resinas o pequenas preparaciones rituales secas.",
        "precio_visible": "16,80 EUR",
        "imagen_url": "/imagenes/productos/caldero-hierro-mini.webp",
        "planta_slug": None,
        "publicado": True,
    },
)
