from datetime import date


RITUALES_DEMO = (
    {
        "id": "rit-demo-descanso",
        "slug": "descanso-melisa-lavanda",
        "nombre": "Descanso con melisa y lavanda",
        "contexto_breve": "Preparacion suave para cerrar el dia con hierba, vela blanca y aroma floral.",
        "contenido": "Prepara la infusion, enciende una vela blanca y deja que el aroma floral marque el cierre del dia.",
        "imagen_url": "/fondos/rituales_card.webp",
        "publicado": True,
        "intenciones": ("calma-nocturna",),
        "plantas_relacionadas": ("melisa", "lavanda"),
        "productos_relacionados": (
            "melisa-a-granel-50g",
            "lavanda-flores-40g",
            "vela-lunar-blanca",
        ),
    },
    {
        "id": "rit-demo-limpieza",
        "slug": "limpieza-umbral-romero-ruda",
        "nombre": "Limpieza del umbral con romero y ruda",
        "contexto_breve": "Ritual domestico para renovar la entrada del hogar con humo suave y gesto sobrio.",
        "contenido": "Ordena la entrada, coloca el caldero y usa el romero y la ruda como acompanamiento simbolico.",
        "imagen_url": "/fondos/rituales_card.webp",
        "publicado": True,
        "intenciones": ("limpieza-energetica", "claridad-ritual"),
        "plantas_relacionadas": ("romero",),
        "productos_relacionados": (
            "romero-a-granel-50g",
            "ruda-rama-seca-30g",
            "incienso-ruda-proteccion",
            "caldero-hierro-mini",
        ),
    },
    {
        "id": "rit-demo-lunar",
        "slug": "altar-lunar-cuarzo",
        "nombre": "Altar lunar con cuarzo",
        "contexto_breve": "Composicion sencilla para noches de luna visible con luz blanca y cuarzo limpio.",
        "contenido": "Prepara un pequeno altar, enciende la vela y coloca el cuarzo como punto de atencion serena.",
        "imagen_url": "/fondos/rituales_card.webp",
        "publicado": True,
        "intenciones": ("calma-nocturna", "claridad-ritual"),
        "plantas_relacionadas": ("lavanda",),
        "productos_relacionados": (
            "vela-lunar-blanca",
            "cuarzo-cristal-rodado",
            "cuenco-selenita-pulido",
        ),
    },
    {
        "id": "rit-demo-claridad",
        "slug": "claridad-con-amatista-y-pendulo",
        "nombre": "Claridad con amatista y pendulo",
        "contexto_breve": "Mesa de enfoque para lectura simbolica, revision de notas y pregunta bien formulada.",
        "contenido": "Ordena la mesa, fija una pregunta concreta y usa la amatista con el pendulo como soporte simbolico.",
        "imagen_url": "/fondos/rituales_card.webp",
        "publicado": True,
        "intenciones": ("claridad-ritual",),
        "plantas_relacionadas": ("romero",),
        "productos_relacionados": (
            "amatista-punta-suave",
            "pendulo-laton-dorado",
            "cuenco-selenita-pulido",
        ),
    },
    {
        "id": "rit-demo-gratitud",
        "slug": "gratitud-con-vela-miel",
        "nombre": "Gratitud con vela miel",
        "contexto_breve": "Ritual breve de mesa para cerrar semana con una nota de gratitud y luz calida.",
        "contenido": "Enciende la vela miel, escribe tres notas de gratitud y acompana el cierre con una infusion suave.",
        "imagen_url": "/fondos/rituales_card.webp",
        "publicado": True,
        "intenciones": ("gratitud-cotidiana", "calma-nocturna"),
        "plantas_relacionadas": ("manzanilla",),
        "productos_relacionados": (
            "vela-miel-dorada",
            "manzanilla-dulce-60g",
            "cuarzo-cristal-rodado",
        ),
    },
)

REGLAS_CALENDARIO_DEMO = (
    {
        "id": "reg-demo-descanso-marzo",
        "ritual_slug": "descanso-melisa-lavanda",
        "nombre": "Cierre suave de finales de marzo",
        "fecha_inicio": date(2026, 3, 1),
        "fecha_fin": date(2026, 4, 30),
        "prioridad": 10,
        "activa": True,
    },
    {
        "id": "reg-demo-limpieza-equinoccio",
        "ritual_slug": "limpieza-umbral-romero-ruda",
        "nombre": "Limpieza del umbral en tramo de equinoccio",
        "fecha_inicio": date(2026, 3, 20),
        "fecha_fin": date(2026, 4, 15),
        "prioridad": 20,
        "activa": True,
    },
    {
        "id": "reg-demo-lunar-creciente",
        "ritual_slug": "altar-lunar-cuarzo",
        "nombre": "Ventana lunar de observacion y quietud",
        "fecha_inicio": date(2026, 3, 27),
        "fecha_fin": date(2026, 4, 3),
        "prioridad": 5,
        "activa": True,
    },
    {
        "id": "reg-demo-claridad-abril",
        "ritual_slug": "claridad-con-amatista-y-pendulo",
        "nombre": "Revision ritual de comienzo de ciclo",
        "fecha_inicio": date(2026, 3, 28),
        "fecha_fin": date(2026, 5, 10),
        "prioridad": 30,
        "activa": True,
    },
    {
        "id": "reg-demo-gratitud-semanal",
        "ritual_slug": "gratitud-con-vela-miel",
        "nombre": "Cierre de semana con gratitud",
        "fecha_inicio": date(2026, 4, 1),
        "fecha_fin": date(2026, 5, 31),
        "prioridad": 40,
        "activa": True,
    },
)
